### ISSUE TITLE
Pass Variables to launch an APP directly using URL

### ISSUE THREAD

**Issue by ne0YT** [kasmtech/KasmVNC#171]
**Is your feature request related to a problem? Please describe.**
I would love to directly run an app on my linux machine which sometimes uses different parameters.
I would like to have a few links in my favorite bar to launch it directly (after logging in of course)

**Describe the solution you'd like**
I would like to pass an app with it's variables directly in the url and also use the username I logged in in kasmvnc to pass as a variable.

**Comment by mmcclaskey** [comment]
This is not possible with KasmVNC and is not likely something that we would add to KasmVNC. It is possible we would add it to the Kasm Workspaces platform, since we do have that exact capability for Windows RemoteApp.

The latest version coming out in a few weeks adds support for arbitrary Unix Socket redirection. You could then easily modify noVNC to talk to a Unix socket on the server side. You would have to write your own code to handle the comms to the unix socket.

https://www.kasmweb.com/kasmvnc/docs/master/developer_api.html#unix-relay

**Comment by ne0YT** [comment]
@mmcclaskey 
can I smh define one static command, which will be run every time the connection opens? maybe from the serverside?
