### ISSUE TITLE
Multi User login on a single port

### ISSUE THREAD

**Issue by ne0YT** [kasmtech/KasmVNC#173]
**Is your feature request related to a problem? Please describe.**
I would like to be able to login with three different users on the same interface.
Is this somehow possible or does the login only work for one user?

**Describe the solution you'd like**
I would like to be able to login wiht different users without starting multiple vncserver instances.

**Comment by mmcclaskey** [comment]
This is not possible due to the over all architecture of VNC. The process needs to run as the user. So that means you need 3 KAsmvNC processes running for 3 users and each needs its own port. Significant changes would be needed to support a different architecture where there was only 1 KasmVNC process for N number of users. With Xvnc, X11 is literally compiled into it. You would have to decouple X11 from Xvnc.

**Comment by ne0YT** [comment]
@mmcclaskey 
Don't you think there could be a "meta"-process running on top, which only checks the login and then routes the user to his session?
It would really help me a lot.

**Comment by mmcclaskey** [comment]
It is possible, and something to consider if we make a systemd service, but it would be a long way out on the roadmap. You could likely develop something that sits in front of KasmVNC to do such a thing.
