### ISSUE TITLE
No access after install the Kasm VNC

### ISSUE THREAD

**Issue by billcastroTT** [kasmtech/KasmVNC#210]
Hello Everyone,

I'm running ubuntu 23.04 in a cloud machine.
I followed the instructions to install the Kasm VNC.
When I check the vncserver it shows:
KasmVNC server sessions:

X DISPLAY #     PROCESS ID
:1              1034

However, when I try to access the VNC  using a web browser (Microsoft Edge) by entering the cloud machine IP:PORTNUMBER I got an error in the browser saying "Hmmm... can't reach this page".
I do access the cloud machine via ssh with no issues but the VNC server seems not to be working properly.
Any ideas?

Thank you.

**Comment by mmcclaskey** [comment]
First, we don't have a build for 23.04, the closest we have is 22.04, so it is not guaranteed to work. Given that Ubuntu 23.04 is not supported, what package did you install.

Can you provide output of these commands...
```
ss -l -t -p
Xvnc -version
```

The first command should verify the port that Xvnc is listening on and tell us if Xvnc is actually running and listening on the correct port.

Next, if you verify that Xvnc is listening and on the correct port, try to curl it using the loopback address.

```
curl https://127.0.0.1/vnc.html -k -v
```

If you get any response, then it is listening, it will get denied, likely with a 401, because the curl did not send an authenticated request. If curl works, but your browser does not, then it is likely your cloud environment. Each cloud environment is different, with respect to how you open up ports to the public. Some, such as Oracle, require you to not only edit the cloud security list settings in the VPC settings, but also you have to edit iptables rules on the VM.

**Comment by billcastroTT** [comment]
> First, we don't have a build for 23.04, the closest we have is 22.04, so it is not guaranteed to work. Given that Ubuntu 23.04 is not supported, what package did you install.
> 
> Can you provide output of these commands...
> 
> ```
> ss -l -t -p
> Xvnc -version
> ```
> 
> The first command should verify the port that Xvnc is listening on and tell us if Xvnc is actually running and listening on the correct port.
> 
> Next, if you verify that Xvnc is listening and on the correct port, try to curl it using the loopback address.
> 
> ```
> curl https://127.0.0.1/vnc.html -k -v
> ```
> 
> If you get any response, then it is listening, it will get denied, likely with a 401, because the curl did not send an authenticated request. If curl works, but your browser does not, then it is likely your cloud environment. Each cloud environment is different, with respect to how you open up ports to the public. Some, such as Oracle, require you to not only edit the cloud security list settings in the VPC settings, but also you have to edit iptables rules on the VM.

Hello @mmcclaskey 

I've just started over. Now with Debian11 bulleyes. 
Here is the output from your first request.

State     Recv-Q    Send-Q         Local Address:Port         Peer Address:Port    Process
LISTEN    0         128                  0.0.0.0:ssh               0.0.0.0:*        users:(("sshd",pid=5163,fd=3))
LISTEN    0         5                    0.0.0.0:8444              0.0.0.0:*        users:(("Xvnc",pid=10591,fd=10))
LISTEN    0         128                     [::]:ssh                  [::]:*        users:(("sshd",pid=5163,fd=4))

For me it looks like it is listening on port 8444.
Here is the version per your command.
Xvnc KasmVNC 1.2.0.2af2e661e9906b5778644f6e2fbe1f51cebb337a - built Sep 13 2023 23:47:58
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12010000, The X.Org Foundation

Lastly, your last command
*   Trying 127.0.0.1:443...
* connect to 127.0.0.1 port 443 failed: Connection refused
* Failed to connect to 127.0.0.1 port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 443: Connection refused

Now, I'm no expert but it looks like it is listening on port 8444 but the last command tried port 443?
Should I change any conf file?

Thank you for the help.
