### ISSUE TITLE
Wrong auth credentials -> blank page w/o asking for password

### ISSUE THREAD

**Issue by ledestin** [kasmtech/KasmVNC#24]
In case of wrong credentials, it makes sense to ask for user/password. But that doesn't happen.

In this case, all I get is a blank page, presumably because a few files the browser tries to load are 401'ed.

@clbr

**Comment by clbr** [comment]
Not mine, that is up to the browser. And browsers cache wrong
credentials too - enter wrong ones, server says no, browser won't ask
again until you clear caches. Plenty of google results.

**Comment by kasmtech** [comment]
@ledestin, We need to fix this by implementing our own authentication and session handling rather than relying on basic auth. We will do that at a later point, so for now we will just have to deal with basic auth. @clbr, I believe that if the server returns a 401 the browser should prompt the user to enter credentials again, according to the spec. But it seems that each browsers behavior might be different and Basic Auth probably just needs to go away. But for now at least we will keep it.
