### ISSUE TITLE
Can we disable password for the kasmweb/debian-bookworm-desktop image?

### ISSUE THREAD

**Issue by imthenachoman** [kasmtech/KasmVNC#247]
Is there an environmental variable or something we can use to disable the username/password prompt?

Also, anyway to allow HTTP and disable HTTPS redirect?

**Comment by mmcclaskey** [comment]
I believe you can disable SSL
https://www.kasmweb.com/kasmvnc/docs/latest/configuration.html#network
network.ssl.require_ssl

I don't believe you can disable authentication. You could, however, statically embed the authorization header in a proxy that sits in front of KasmVNC, since KasmVNC uses HTTP Basic Authorization.

https://stackoverflow.com/questions/43821612/authorization-header-in-nginx-for-proxying-to-basic-auth-backend-doest-work

**Comment by imthenachoman** [comment]
I'm running KasmVNC through Docker. Let me see if I can figure out how to make these changes.

**Comment by mmcclaskey** [comment]
Just map in your custom config to /etc/kasmvnc/kasmvnc.yaml, most likely will do the trick. You can, of course create your own custom docker image, but it is not necessary.

**Comment by imthenachoman** [comment]
Yeah. I will play with this.

So you're saying, even if I disable SSL, I'll still have to login when I go to http://...?

**Comment by mattmcclaskey** [comment]
Yes that is correct. Disabling SSL is not really something we account for (test and consider), but it is technically there for people to disable.
