### ISSUE TITLE
Any way to alter/force default configuration?

### ISSUE THREAD

**Issue by MrMEEE** [kasmtech/KasmVNC#266]
[**Is your feature request related to a problem? Please describe.**
 I want to know if it is possible to enable things like game mode and fullscreen by default??

**Describe the solution you'd like**
Some kind of configuration file where default options can be set

**Additional context**
Basically the same question as (https://github.com/kasmtech/workspaces-issues/issues/601)

**Comment by mmcclaskey** [comment]
Due to browser security, some actions require a `user driven event` in javascript. Pointer lock (and game mode which uses pointer lock) is a browser feature that requires user interaction. In other words, the javascript that turns on pointer lock, must have been triggered by a user clicking on a button or something like that. This security protection keeps malicious apps from being able to hold a user hostage, constantly putting something full screen with pointer lock, unable to get out. 

We currently have no plans to implement a way to default to full screen, game mode, and/or pointer lock. However, many other settings can be configured in the default kasmvnc.yaml configuration. https://www.kasmweb.com/kasmvnc/docs/latest/configuration.html
