### ISSUE TITLE
Can Kasmvnc disable basic authentication? Alternatively, you can cancel the input of your account/password

### ISSUE THREAD

**Issue by baoxukang123** [kasmtech/KasmVNC#268]
I plan to use kasmvnc to embed my program, but it requires entering an account and password, which is difficult to solve in iframes. Therefore, I want to cancel the basic authentication of kasmvnc

**Comment by mmcclaskey** [comment]
You can put nginx (or your favorite reverse proxy) in front of KasmVNC and inject the basic authorization header at the proxy. Alternatively, you can disable basic auth in KasmVNC by passing the `-disableBasicAuth` flag to vncserver. This is not supported by the yaml configuration, so you have to pass it to vncserver as an additional flag. If you disable authentication it will also disable the API, since the API handler will not be able to check authorization if you are not authenticated. If you don't plan on using the API service then you should be fine.

**Comment by baoxukang123** [comment]
Okay, I did it. Thank you
