### ISSUE TITLE
Auto start KasmVNC on boot in VM.

### ISSUE THREAD

**Issue by GogoFC** [kasmtech/KasmVNC#283]
I'm running Kasm on a Ubuntu VM.

What is a proper way of Auto starting KasmVNC so that it's reliable?

I tried to run a cronjob with `@reboot vncserver` that didn't work. 

I'd though of making my own systemd service  but was worried that vncserver might start it again on a different port which would break my port forwarding.

So then I snapped and ran a script at reboot via crontab. 
```bash
#!/bin/bash
ssh localhost vncserver
```

Later I read here [here](https://github.com/kasmtech/KasmVNC/issues/118) and see that other users did their own Systemd services, but I already start it via SSH.  Is that the way to go?

I don't know how long it will keep running without reboot.

**Comment by mmcclaskey** [comment]
Personally, if I were looking to ensure KasmVNC was started on boot, for specific users on specific ports, I would use systemd. But at this time, we have not looked into this for ourselves, so I can't provide any specific feedback.

**Comment by GogoFC** [comment]
Thanks

**Comment by mhadjih2** [comment]
A bit of a shame that such a nice product can't be invoked at system-start by systemd or other instructions because nobody but potential customers seem to care about this function, as I read multiple threads already about this topic, but no answers are provided and the standard approach is not working due to the inner workings of KasmVNC.
