### ISSUE TITLE
Attach to physical screen session

### ISSUE THREAD

**Issue by kennyparsons** [kasmtech/KasmVNC#54]
I'd like to use kasmvnc to attach to a screen already in use (think of a remote help tool). 

Currently, my x server is running on `:1024`. When I modify the kasmserver easy start script to use that display, kasm errors out, saying a vnc server already exists on it. Can a flag be added to attach to an existing display port if it already exists (whether vnc or physical, but definitely physical)?

**Comment by mmcclaskey** [comment]
We have a branch open that would allow you to do this. It adds a new binary, kasmxproxy, which will proxy an X session that is on a physical card to a KasmVNC session. You would have to build the code yourself though since it is not in a release yet. Also, be forewarned that if a physical monitor is in use, you should not use the -r option which auto resizes the session if the client is set to auto resize. Physical monitors would take issue with sizes they don't support.

https://github.com/kasmtech/KasmVNC/tree/feature/KASM-1883_x_proxy

**Comment by gou4shi1** [comment]
any update?

**Comment by Zak-Bahm** [comment]
This appears to have been merged in with the [v0.9.3 beta release](https://github.com/kasmtech/KasmVNC/releases/tag/v0.9.3-beta) but I can't find any mention of it in the documentation. Is it currently possible to attach to a physical screen using kasmvnc v1.0.0+ and if so how is that configured?

**Comment by mmcclaskey** [comment]
Yes. You essentially start KasmVNC without a desktop environment. Manually edit .vnc/xstartup to not start your DE. After vncserver has started, you can then use kasmxproxy, which will proxy a real X session to the KasmVNC X session. 

**PER THE DOCS, IF YOU ARE USING A PHYSICAL SCREEN, DO NOT USE THE "-r" OPTION!!!** This will dynamically resize the backend resolution to match the client's resolution and you can't do that with a physical monitor attached, it may damage your hardware. Instead, you need to manually change your resolution to one supported by your hardware combination (video card and monitor).

https://www.kasmweb.com/kasmvnc/docs/latest/man/kasmxproxy.html
