### ISSUE TITLE
Cannot add Brave image

### ISSUE THREAD

**Issue by abhinav-TB** [kasmtech/KasmVNC#88]
` Failed to pull image (kasmweb/brave) : 404 Client Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=kasmweb%2Fbrave: Not Found ("manifest for kasmweb/brave:latest not found: manifest unknown: manifest unknown")
`
getting the above error while trying to add brave image

![image](https://user-images.githubusercontent.com/54744701/151768702-0bcd85be-6272-477c-9d27-9fd45d5a8ee2.png)
![image](https://user-images.githubusercontent.com/54744701/151768822-c72c91aa-f1dd-4a35-9d5f-e584f117d019.png)

**Comment by abhinav-TB** [comment]
full error log
![image](https://user-images.githubusercontent.com/54744701/151769134-e1599f56-7895-4dbb-b681-dbcadebb5d8e.png)

**Comment by j-travis** [comment]
Hi, since this issue relates to Kasm Workspaces it belongs in  https://github.com/kasmtech/workspaces-issues/ .

Please be aware we don't publish a `latest` tag which relates to the error message you are seeing. I do see in the screenshot that you have specified the rolling tag which we do indeed have. 

Brave is available for amd64 systems but not arm64.

Also, please be aware that a similar error is reported if you don't have enough disk space. See https://github.com/kasmtech/workspaces-issues/issues/114 for details
