### ISSUE TITLE
command not found when installing kasmvncserver on debian

### ISSUE THREAD

**Issue by pauleastus2000** [kasmtech/KasmVNC#93]

**Comment by mmcclaskey** [comment]
@pauleastus2000 , can you please provide the output from the following commands.

`uname -a`
`cat /etc/os-release`

**Comment by pauleastus2000** [comment]
I got it installed but when i try to start the service it says (vncserver :
command not found)

i got it installed in ubuntu bionic 18.04LTS with gnome desktop

**Comment by mmcclaskey** [comment]
@pauleastus2000 , can you please provide the output from the following commands.

uname -a
cat /etc/os-release

**Comment by pauleastus2000** [comment]
this is the output

Linux paul-Standard-PC-i440FX-PIIX-1996 5.4.0-84-generic #94~18.04.1-Ubuntu
SMP Thu Aug 26 23:17:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="
https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by mmcclaskey** [comment]
Can you please try reinstalling one more time, ensure you run both:
dpkg -i <package-name>.deb
apt-get install -f

I suspect you missed the second command, but if it still does not work after that, please provide the output from running those two commands. Also please follow the rest of the instructions in the README after the above two are complete.

**Comment by pauleastus2000** [comment]
Will do.

**Comment by pauleastus2000** [comment]
Does the kasm workspace have the vnc installed already because i will use
the workspace for ease of getting the vnc.

**Comment by pauleastus2000** [comment]
this is the file i used to download the package

wget
https://github.com/kasmtech/KasmVNC/releases/download/v0.9.1-beta/KasmVNC_0.9.1-beta_Ubuntu_18.04.tar.gz
| sudo tar gz --strip 1 -C /

**Comment by pauleastus2000** [comment]
this is the output for sudo dpkg -i .deb
dpkg: error: cannot access archive '.deb': No such file or directory

**Comment by pauleastus2000** [comment]
i can log u in remotely to figure out what is the problem

**Comment by mmcclaskey** [comment]
No, I'm sorry, I can't provide that level of support. 

You are not installing the latest version, nor are you following the directions. Here are the directions, copied directly from the README.md.

wget https://github.com/kasmtech/KasmVNC/releases/download/v0.9.2-beta/kasmvncserver_ubuntu_bionic_0.9.2_amd64.deb

sudo dpkg -i kasmvncserver_*.deb
sudo apt-get -f install

# We provide an example script to run KasmVNC at #
# /usr/share/doc/kasmvncserver/examples/kasmvncserver-easy-start. It runs a VNC
# server on display :10 and on interface 0.0.0.0. If you're happy with those
# defaults you can just use it as is:
sudo ln -s /usr/share/doc/kasmvncserver/examples/kasmvncserver-easy-start /usr/bin/

# Add your user to the ssl-cert group
sudo addgroup $USER ssl-cert
# You will need to re-connect in order to pick up the group change

# Create ~/.vnc directory and corresponding files.
kasmvncserver-easy-start -d && kasmvncserver-easy-start -kill

# Modify vncstartup to launch your environment of choice, in this example LXDE
# This may be optional depending on your system configuration
echo '/usr/bin/lxsession -s LXDE &' >> ~/.vnc/xstartup

# Start KasmVNC with debug logging:
kasmvncserver-easy-start -d

# Tail the logs
tail -f ~/.vnc/`hostname`:10.log
