### ISSUE TITLE
Incomplete display with local resize option & Mouse pointer edge swiping not work on touchscreen devices

### ISSUE THREAD

**Issue by Kissycat** [kasmtech/KasmVNC#99]
Just like the pictures...

![S20425-09505083](https://user-images.githubusercontent.com/20614068/165025306-d9520efa-25eb-438e-b74a-898ba5343b2f.png)
![S20425-09512448(1)](https://user-images.githubusercontent.com/20614068/165025322-df43c48b-1ae7-4745-9950-52a43e625ce9.png)

And it is appeared after I upgrade kasmvnc from release "KasmVNC 0.9.2 Beta" to [d829572](https://github.com/kasmtech/KasmVNC/commit/d829572a9c86535df9434adbb4ba696a43417d35) , it used to work fine.
Local resize is useful, because the touchscreen devices can not call the hidden dock out in fullscreen (remote resize mode), even with a mouse. But a smaller display could.

![image](https://user-images.githubusercontent.com/20614068/165026297-69437e9e-7861-49cb-8c34-9d196bafd9f2.png)
![无标题](https://user-images.githubusercontent.com/20614068/165026398-1ebe06a5-aec6-4d83-8346-604da4c40a9f.png)

**Comment by CDLLY** [comment]
And they are all chrome 100 on an Android 11 phone, Windows 11 laptop with touchscreen, Windows 10 Desktop.

**Comment by mmcclaskey** [comment]
Hello, thanks for reporting the issues. I may have questions later when we come to testing for a new release, if we are unable to reproduce.

**Comment by CDLLY** [comment]
OK, I would like to help, as long as I can.

**Comment by mmcclaskey** [comment]
If you would like to take a look at it, I can give you a quick tip for working with the front end code more easily. The following instructions assume you have KasmVNC installed on the server.

First make a fork of our project and replace our URL below with your fork's git url.

```
cd /usr/share/kasmvnc
rm -rf www
git clone https://github.com/kasmtech/noVNC.git www
cd www
git checkout bugfix/touchscreen_sizing
```

Modify the code to run directly without a webpack, as covered in docs/DEVELOP.md

```
sed -i 's#<script type="module" crossorigin="use-credentials" src="app/ui.js"></script-->#<script type="module" crossorigin="use-credentials" src="app/ui.js"></script>#' vnc.html
sed -i 's#<!--link rel="stylesheet" href="app/styles/base.css">#<link rel="stylesheet" href="app/styles/base.css">#' vnc.html
sed -i 's#import "core-js/stable";#//import "core-js/stable";#' app/ui.js
sed -i 's#import "regenerator-runtime/runtime";#//import "regenerator-runtime/runtime";#' app/ui.js
```

You can now access KasmVNC that will run directly on the web code rather than the webpack. **You will need to go to vnc.html instead of index.html.**

Once complete with code changes, run the following before committing to your git repo. This reverts the changes that allowed you to run the web code directly without the webpack.

```
cd /usr/share/kasmvnc/www
sed -i 's#<script type="module" crossorigin="use-credentials" src="app/ui.js"></script>#<script type="module" crossorigin="use-credentials" src="app/ui.js"></script-->#' vnc.html
sed -i 's#<link rel="stylesheet" href="app/styles/base.css">#<!--link rel="stylesheet" href="app/styles/base.css">#' vnc.html
sed -i 's#//import "core-js/stable";#import "core-js/stable";#' app/ui.js
sed -i 's#//import "regenerator-runtime/runtime";#import "regenerator-runtime/runtime";#' app/ui.js
```

Now you can commit your changes to your forked repo and then make a pull request back to this project.

**Comment by Kissycat** [comment]
Thanks a lot, I may give a try.  : )
